### ISSUE TITLE
Modal zIndex Bug with Leaflet

### ISSUE THREAD

**Issue by Gugustinette** [stlbucket/nuxt-ui-modal-leaflet-overlay-bug#1]
Hey !

Just saw your problem with modals using my lib.
I don't know if it's an intentional behavior, but looks like by default, Leaflet's CSS wants to go high lol

This little tweak fixed the problem for me ([source](https://wordpress.org/support/topic/leaflet-map-z-index-and-css/)) :
```vue
<style>
.leaflet-container {
  z-index: 0 !important;
}
</style>
```

**Comment by stlbucket** [comment]
@Gugustinette - thank you, that is the fix
